### ISSUE TITLE
Two heights and no widths

### ISSUE THREAD

**Issue by gerritholl** [loreclem/areadef#1]
When I use the installation at http://clemspace.ch/areadef/ to select an area near Crete with a resolution of 500 metre, I get:

```yaml
crete:
  description: Crete and nearby islands
    proj: eqc
    ellps: WGS84
    units: m
  shape:
    height: 731
    height: 293
  area_extent:
    lower_left_xy: [2584716.7894244194, 3854960.1286649713]
    upper_right_xy: [2950317.3753619194, 4001444.5036649713]
```

Note that the shape has two heights and no width.  The first one of those heights should be width.
